/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C
 * Generated (UTC): 2026-02-19T00:36:53Z
 * Module registry: spec/module_registry.yaml
 * Module registry version: 1
 */
    #include "ewts/module_keys.h"
    #include <string.h>

    const ewts_module_entry ewts_modules[] = {
        {"ngen", "NGEN", "ngen framework"},
        {"cfe-s", "CFE", "Conceptual Functional Equivalent to the National Water Model (Schaake)"},
        {"cfe-x", "CFE", "Conceptual Functional Equivalent to the National Water Model (Xianjiang)"},
        {"forcing", "FORCING", "Forcing Engine"},
        {"lasam", "LASAM", "Lumped Arid/Semi-arid Model"},
        {"lstm", "LSTM", "Long Short-Term Memory Networks Model"},
        {"noah-owp-modular", "NOAHOWP", "Noah OWP Land Surface Model"},
        {"pet", "PET", "Potential Evapotranspiration Model"},
        {"sac-sma", "SACSMA", "Sacramento Soil Moisture Accounting Model"},
        {"sft", "SFT", "Soil Freeze-thaw Model"},
        {"snow-17", "SNOW17", "Snow Cccumulation and Melt Model"},
        {"smp", "SMP", "Soil Moisture Profiles Model"},
        {"topmodel", "TOPMODEL", "Physically Based, Distributed Watershed Model"},
        {"topoflow-glacier", "TFGLACR", "Glacier Model from the TopoFlow Model"},
        {"t-route", "TROUTE", "T-Route routing"},
        {"ueb", "UEB_BMI", "Utah Energy Balance Model"}
    };

    const size_t ewts_modules_count = sizeof(ewts_modules) / sizeof(ewts_modules[0]);

    const char* ewts_module_id_from_key(const char* key) {
        if (!key) return NULL;
        for (size_t i = 0; i < ewts_modules_count; ++i) {
            if (strcmp(ewts_modules[i].key, key) == 0) {
                return ewts_modules[i].ewts_id;
            }
        }
        return NULL;
    }

    const char* ewts_description_from_key(const char* key) {
        if (!key) return NULL;
        for (size_t i = 0; i < ewts_modules_count; ++i) {
            if (strcmp(ewts_modules[i].key, key) == 0) {
                return ewts_modules[i].description;
            }
        }
        return NULL;
    }

    size_t ewts_keys_from_module_id(const char* ewts_id, const char** out_keys, size_t max_keys) {
        if (!ewts_id) return 0;
        size_t n = 0;
        for (size_t i = 0; i < ewts_modules_count; ++i) {
            if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {
                if (out_keys && n < max_keys) {
                    out_keys[n] = ewts_modules[i].key;
                }
                ++n;
            }
        }
        return n;
    }

    size_t ewts_descriptions_from_module_id(const char* ewts_id, const char** out_descs, size_t max_descs) {
        if (!ewts_id) return 0;
        size_t n = 0;
        for (size_t i = 0; i < ewts_modules_count; ++i) {
            if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {
                if (out_descs && n < max_descs) {
                    out_descs[n] = ewts_modules[i].description;
                }
                ++n;
            }
        }
        return n;
    }

    const char* ewts_first_key_from_module_id(const char* ewts_id) {
        if (!ewts_id) return NULL;
        for (size_t i = 0; i < ewts_modules_count; ++i) {
            if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {
                return ewts_modules[i].key;
            }
        }
        return NULL;
    }

    const char* ewts_first_description_from_module_id(const char* ewts_id) {
        if (!ewts_id) return NULL;
        for (size_t i = 0; i < ewts_modules_count; ++i) {
            if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {
                return ewts_modules[i].description;
            }
        }
        return NULL;
    }
