/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C
 */
#include "ewts/module_keys.h"
#include <string.h>

const ewts_module_entry ewts_modules[] = {
        {"ngen", "NGEN", "ngen framework"},\n    {"cfe-s", "CFE", "Conceptual Functional Equivalent to the National Water Model (Schaake)"},\n    {"cfe-x", "CFE", "Conceptual Functional Equivalent to the National Water Model (Xianjiang)"},\n    {"forcing", "FORCING", "Forcing Engine"},\n    {"lasam", "LASAM", "Lumped Arid/Semi-arid Model"},\n    {"lstm", "LSTM", "Long Short-Term Memory Networks Model"},\n    {"noah-owp-modular", "NOAHOWP", "Noah OWP Land Surface Model"},\n    {"pet", "PET", "Potential Evapotranspiration Model"},\n    {"sac-sma", "SACSMA", "Sacramento Soil Moisture Accounting Model"},\n    {"sft", "SFT", "Soil Freeze-thaw Model"},\n    {"snow-17", "SNOW17", "Snow Cccumulation and Melt Model"},\n    {"smp", "SMP", "Soil Moisture Profiles Model"},\n    {"topmodel", "TOPMODEL", "Physically Based, Distributed Watershed Model"},\n    {"topoflow-glacier", "TFGLACR", "Glacier Model from the TopoFlow Model"},\n    {"t-route", "TROUTE", "T-Route routing"},\n    {"ueb", "UEB_BMI", "Utah Energy Balance Model"}
};

const size_t ewts_modules_count = sizeof(ewts_modules) / sizeof(ewts_modules[0]);

const char* ewts_module_id_from_key(const char* key) {
    if (!key) return NULL;
    for (size_t i = 0; i < ewts_modules_count; ++i) {
        if (strcmp(ewts_modules[i].key, key) == 0) {
            return ewts_modules[i].ewts_id;
        }
    }
    return NULL;
}

const char* ewts_description_from_key(const char* key) {
    if (!key) return NULL;
    for (size_t i = 0; i < ewts_modules_count; ++i) {
        if (strcmp(ewts_modules[i].key, key) == 0) {
            return ewts_modules[i].description;
        }
    }
    return NULL;
}

size_t ewts_keys_from_module_id(const char* ewts_id, const char** out_keys, size_t max_keys) {
    if (!ewts_id) return 0;
    size_t n = 0;
    for (size_t i = 0; i < ewts_modules_count; ++i) {
        if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {
            if (out_keys && n < max_keys) {
                out_keys[n] = ewts_modules[i].key;
            }
            ++n;
        }
    }
    return n;
}

size_t ewts_descriptions_from_module_id(const char* ewts_id, const char** out_descs, size_t max_descs) {
    if (!ewts_id) return 0;
    size_t n = 0;
    for (size_t i = 0; i < ewts_modules_count; ++i) {
        if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {
            if (out_descs && n < max_descs) {
                out_descs[n] = ewts_modules[i].description;
            }
            ++n;
        }
    }
    return n;
}

const char* ewts_first_key_from_module_id(const char* ewts_id) {
    if (!ewts_id) return NULL;
    for (size_t i = 0; i < ewts_modules_count; ++i) {
        if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {
            return ewts_modules[i].key;
        }
    }
    return NULL;
}

const char* ewts_first_description_from_module_id(const char* ewts_id) {
    if (!ewts_id) return NULL;
    for (size_t i = 0; i < ewts_modules_count; ++i) {
        if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {
            return ewts_modules[i].description;
        }
    }
    return NULL;
}
