/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C
 */
#ifndef EWTS_LOG_LEVELS_H
#define EWTS_LOG_LEVELS_H

#ifdef __cplusplus
extern "C" {
#endif

static inline const char* ewts_log_level_name(int level) {
    switch (level) {
    case 0: return "NOTSET";
case 10: return "DEBUG";
case 20: return "INFO";
case 30: return "WARNING";
case 40: return "ERROR";
case 40: return "SEVERE";
case 50: return "FATAL";
case 50: return "CRITICAL";
        default: return "INFO";
    }
}

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // EWTS_LOG_LEVELS_H
