/* AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by tools/generate_language_constants.py
 * Language: C
 * Generated (UTC): 2026-02-19T00:36:53Z
 * Module registry: spec/module_registry.yaml
 * Module registry version: 1
 */

#ifndef EWTS_MODULE_CONSTANTS_H
#define EWTS_MODULE_CONSTANTS_H

/* Auto-generated constants for module keys and EWTS IDs. */

#define EWTS_KEY_NGEN "ngen"
#define EWTS_ID_NGEN "NGEN"

#define EWTS_KEY_CFE_S "cfe-s"
#define EWTS_ID_CFE_S "CFE"

#define EWTS_KEY_CFE_X "cfe-x"
#define EWTS_ID_CFE_X "CFE"

#define EWTS_KEY_FORCING "forcing"
#define EWTS_ID_FORCING "FORCING"

#define EWTS_KEY_LASAM "lasam"
#define EWTS_ID_LASAM "LASAM"

#define EWTS_KEY_LSTM "lstm"
#define EWTS_ID_LSTM "LSTM"

#define EWTS_KEY_NOAH_OWP_MODULAR "noah-owp-modular"
#define EWTS_ID_NOAH_OWP_MODULAR "NOAHOWP"

#define EWTS_KEY_PET "pet"
#define EWTS_ID_PET "PET"

#define EWTS_KEY_SAC_SMA "sac-sma"
#define EWTS_ID_SAC_SMA "SACSMA"

#define EWTS_KEY_SFT "sft"
#define EWTS_ID_SFT "SFT"

#define EWTS_KEY_SNOW_17 "snow-17"
#define EWTS_ID_SNOW_17 "SNOW17"

#define EWTS_KEY_SMP "smp"
#define EWTS_ID_SMP "SMP"

#define EWTS_KEY_TOPMODEL "topmodel"
#define EWTS_ID_TOPMODEL "TOPMODEL"

#define EWTS_KEY_TOPOFLOW_GLACIER "topoflow-glacier"
#define EWTS_ID_TOPOFLOW_GLACIER "TFGLACR"

#define EWTS_KEY_T_ROUTE "t-route"
#define EWTS_ID_T_ROUTE "TROUTE"

#define EWTS_KEY_UEB "ueb"
#define EWTS_ID_UEB "UEB_BMI"

#endif  /* EWTS_MODULE_CONSTANTS_H */
