# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/generate_language_constants.py
from __future__ import annotations

LEVELS = {'NOTSET': 0, 'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'ERROR': 40, 'SEVERE': 40, 'FATAL': 50, 'CRITICAL': 50}

def log_level_name(level: int) -> str:
    for name, val in LEVELS.items():
        if val == level:
            return name
    return "INFO"
