# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/generate_language_constants.py
# Generated (UTC): 2026-03-09T15:08:10Z
# Module registry: spec/module_registry.yaml
# Module registry version: 1

from __future__ import annotations
from enum import Enum

class ModuleKey(str, Enum):
    NGEN = "ngen"
    CFE_S = "cfe-s"
    CFE_X = "cfe-x"
    CFE = "cfe"
    FORCING = "forcing"
    LASAM = "lasam"
    LSTM = "lstm"
    NOAH_OWP_MODULAR = "noah-owp-modular"
    PET = "pet"
    SAC_SMA = "sac-sma"
    SFT = "sft"
    SNOW_17 = "snow-17"
    SMP = "smp"
    TOPMODEL = "topmodel"
    TOPOFLOW_GLACIER = "topoflow-glacier"
    T_ROUTE = "t-route"
    UEB = "ueb"


NGEN_KEY = "ngen"
CFE_S_KEY = "cfe-s"
CFE_X_KEY = "cfe-x"
CFE_KEY = "cfe"
FORCING_KEY = "forcing"
LASAM_KEY = "lasam"
LSTM_KEY = "lstm"
NOAH_OWP_MODULAR_KEY = "noah-owp-modular"
PET_KEY = "pet"
SAC_SMA_KEY = "sac-sma"
SFT_KEY = "sft"
SNOW_17_KEY = "snow-17"
SMP_KEY = "smp"
TOPMODEL_KEY = "topmodel"
TOPOFLOW_GLACIER_KEY = "topoflow-glacier"
T_ROUTE_KEY = "t-route"
UEB_KEY = "ueb"

NGEN_ID = "NGEN"
CFE_S_ID = "CFE"
CFE_X_ID = "CFE"
CFE_ID = "CFE"
FORCING_ID = "FORCING"
LASAM_ID = "LASAM"
LSTM_ID = "LSTM"
NOAH_OWP_MODULAR_ID = "NOAHOWP"
PET_ID = "PET"
SAC_SMA_ID = "SACSMA"
SFT_ID = "SFT"
SNOW_17_ID = "SNOW17"
SMP_ID = "SMP"
TOPMODEL_ID = "TOPMODEL"
TOPOFLOW_GLACIER_ID = "TFGLACR"
T_ROUTE_ID = "TROUTE"
UEB_ID = "UEB_BMI"

__all__ = [
    "ModuleKey",
    "NGEN_KEY", "NGEN_ID",
    "CFE_S_KEY", "CFE_S_ID",
    "CFE_X_KEY", "CFE_X_ID",
    "CFE_KEY", "CFE_ID",
    "FORCING_KEY", "FORCING_ID",
    "LASAM_KEY", "LASAM_ID",
    "LSTM_KEY", "LSTM_ID",
    "NOAH_OWP_MODULAR_KEY", "NOAH_OWP_MODULAR_ID",
    "PET_KEY", "PET_ID",
    "SAC_SMA_KEY", "SAC_SMA_ID",
    "SFT_KEY", "SFT_ID",
    "SNOW_17_KEY", "SNOW_17_ID",
    "SMP_KEY", "SMP_ID",
    "TOPMODEL_KEY", "TOPMODEL_ID",
    "TOPOFLOW_GLACIER_KEY", "TOPOFLOW_GLACIER_ID",
    "T_ROUTE_KEY", "T_ROUTE_ID",
    "UEB_KEY", "UEB_ID",
]
