# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/generate_language_constants.py
# Generated (UTC): 2026-03-20T20:06:56Z
# Module registry: spec/module_registry.yaml
# Module registry version: 1

from __future__ import annotations
from enum import Enum

class ModuleKey(str, Enum):
    FORCING = "forcing"
    LSTM = "lstm"
    TOPOFLOW_GLACIER = "topoflow-glacier"
    T_ROUTE = "t-route"


FORCING_KEY = "forcing"
LSTM_KEY = "lstm"
TOPOFLOW_GLACIER_KEY = "topoflow-glacier"
T_ROUTE_KEY = "t-route"

FORCING_ID = "FORCING"
LSTM_ID = "LSTM"
TOPOFLOW_GLACIER_ID = "TFGLACR"
T_ROUTE_ID = "TROUTE"

__all__ = [
    "ModuleKey",
    "FORCING_KEY", "FORCING_ID",
    "LSTM_KEY", "LSTM_ID",
    "TOPOFLOW_GLACIER_KEY", "TOPOFLOW_GLACIER_ID",
    "T_ROUTE_KEY", "T_ROUTE_ID",
]
