# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/generate_language_constants.py
from __future__ import annotations
from typing import Dict, List, Optional

KEY_TO_EWTS_ID: Dict[str, str] = {'ngen': 'NGEN', 'cfe-s': 'CFE', 'cfe-x': 'CFE', 'forcing': 'FORCING', 'lasam': 'LASAM', 'lstm': 'LSTM', 'noah-owp-modular': 'NOAHOWP', 'pet': 'PET', 'sac-sma': 'SACSMA', 'sft': 'SFT', 'snow-17': 'SNOW17', 'smp': 'SMP', 'topmodel': 'TOPMODEL', 'topoflow-glacier': 'TFGLACR', 't-route': 'TROUTE', 'ueb': 'UEB_BMI'}
KEY_TO_DESCRIPTION: Dict[str, str] = {'ngen': 'ngen framework', 'cfe-s': 'Conceptual Functional Equivalent to the National Water Model (Schaake)', 'cfe-x': 'Conceptual Functional Equivalent to the National Water Model (Xianjiang)', 'forcing': 'Forcing Engine', 'lasam': 'Lumped Arid/Semi-arid Model', 'lstm': 'Long Short-Term Memory Networks Model', 'noah-owp-modular': 'Noah OWP Land Surface Model', 'pet': 'Potential Evapotranspiration Model', 'sac-sma': 'Sacramento Soil Moisture Accounting Model', 'sft': 'Soil Freeze-thaw Model', 'snow-17': 'Snow Cccumulation and Melt Model', 'smp': 'Soil Moisture Profiles Model', 'topmodel': 'Physically Based, Distributed Watershed Model', 'topoflow-glacier': 'Glacier Model from the TopoFlow Model', 't-route': 'T-Route routing', 'ueb': 'Utah Energy Balance Model'}
EWTS_ID_TO_KEYS: Dict[str, List[str]] = {'NGEN': ['ngen'], 'CFE': ['cfe-s', 'cfe-x'], 'FORCING': ['forcing'], 'LASAM': ['lasam'], 'LSTM': ['lstm'], 'NOAHOWP': ['noah-owp-modular'], 'PET': ['pet'], 'SACSMA': ['sac-sma'], 'SFT': ['sft'], 'SNOW17': ['snow-17'], 'SMP': ['smp'], 'TOPMODEL': ['topmodel'], 'TFGLACR': ['topoflow-glacier'], 'TROUTE': ['t-route'], 'UEB_BMI': ['ueb']}
EWTS_ID_TO_DESCRIPTIONS: Dict[str, List[str]] = {'NGEN': ['ngen framework'], 'CFE': ['Conceptual Functional Equivalent to the National Water Model (Schaake)', 'Conceptual Functional Equivalent to the National Water Model (Xianjiang)'], 'FORCING': ['Forcing Engine'], 'LASAM': ['Lumped Arid/Semi-arid Model'], 'LSTM': ['Long Short-Term Memory Networks Model'], 'NOAHOWP': ['Noah OWP Land Surface Model'], 'PET': ['Potential Evapotranspiration Model'], 'SACSMA': ['Sacramento Soil Moisture Accounting Model'], 'SFT': ['Soil Freeze-thaw Model'], 'SNOW17': ['Snow Cccumulation and Melt Model'], 'SMP': ['Soil Moisture Profiles Model'], 'TOPMODEL': ['Physically Based, Distributed Watershed Model'], 'TFGLACR': ['Glacier Model from the TopoFlow Model'], 'TROUTE': ['T-Route routing'], 'UEB_BMI': ['Utah Energy Balance Model']}

def ewts_id_from_key(key: str) -> Optional[str]:
    """Return EWTS module id for a key, or None if unknown."""
    return KEY_TO_EWTS_ID.get(key)

def description_from_key(key: str) -> Optional[str]:
    """Return description for a key, or None if unknown."""
    return KEY_TO_DESCRIPTION.get(key)

def keys_from_ewts_id(ewts_id: str) -> List[str]:
    """Return all keys that map to an EWTS id (duplicates supported)."""
    return list(EWTS_ID_TO_KEYS.get(ewts_id, []))

def descriptions_from_ewts_id(ewts_id: str) -> List[str]:
    """Return all descriptions for an EWTS id (duplicates supported)."""
    return list(EWTS_ID_TO_DESCRIPTIONS.get(ewts_id, []))

def first_key_from_ewts_id(ewts_id: str) -> Optional[str]:
    """Return the first key for an EWTS id in registry order, or None."""
    keys = EWTS_ID_TO_KEYS.get(ewts_id)
    return keys[0] if keys else None

def first_description_from_ewts_id(ewts_id: str) -> Optional[str]:
    """Return the first description for an EWTS id in registry order, or None."""
    descs = EWTS_ID_TO_DESCRIPTIONS.get(ewts_id)
    return descs[0] if descs else None
