# AUTO-GENERATED FILE. DO NOT EDIT.
# Generated by tools/generate_language_constants.py
# Generated (UTC): 2026-03-17T15:19:45Z
# Module registry: spec/module_registry.yaml
# Module registry version: 1

from __future__ import annotations
from typing import Dict, List, Optional

KEY_TO_EWTS_ID: Dict[str, str] = {'forcing': 'FORCING', 'lstm': 'LSTM', 'topoflow-glacier': 'TFGLACR', 't-route': 'TROUTE'}
KEY_TO_DESCRIPTION: Dict[str, str] = {'forcing': 'Forcing Engine', 'lstm': 'Long Short-Term Memory Networks Model', 'topoflow-glacier': 'Glacier Model from the TopoFlow Model', 't-route': 'T-Route routing'}
EWTS_ID_TO_KEYS: Dict[str, List[str]] = {'FORCING': ['forcing'], 'LSTM': ['lstm'], 'TFGLACR': ['topoflow-glacier'], 'TROUTE': ['t-route']}
EWTS_ID_TO_DESCRIPTIONS: Dict[str, List[str]] = {'FORCING': ['Forcing Engine'], 'LSTM': ['Long Short-Term Memory Networks Model'], 'TFGLACR': ['Glacier Model from the TopoFlow Model'], 'TROUTE': ['T-Route routing']}

def ewts_id_from_key(key: str) -> Optional[str]:
    """Return EWTS module id for a key, or None if unknown."""
    return KEY_TO_EWTS_ID.get(key)

def description_from_key(key: str) -> Optional[str]:
    """Return description for a key, or None if unknown."""
    return KEY_TO_DESCRIPTION.get(key)

def keys_from_ewts_id(ewts_id: str) -> List[str]:
    """Return all keys that map to an EWTS id (duplicates supported)."""
    return list(EWTS_ID_TO_KEYS.get(ewts_id, []))

def descriptions_from_ewts_id(ewts_id: str) -> List[str]:
    """Return all descriptions for an EWTS id (duplicates supported)."""
    return list(EWTS_ID_TO_DESCRIPTIONS.get(ewts_id, []))

def first_key_from_ewts_id(ewts_id: str) -> Optional[str]:
    """Return the first key for an EWTS id in registry order, or None."""
    keys = EWTS_ID_TO_KEYS.get(ewts_id)
    return keys[0] if keys else None

def first_description_from_ewts_id(ewts_id: str) -> Optional[str]:
    """Return the first description for an EWTS id in registry order, or None."""
    descs = EWTS_ID_TO_DESCRIPTIONS.get(ewts_id)
    return descs[0] if descs else None
