! AUTO-GENERATED FILE. DO NOT EDIT.
! Generated by tools/generate_language_constants.py
! Generated (UTC): 2026-03-03T23:37:52Z
! Module registry: spec/module_registry.yaml
! Module registry version: 1

module ewts_module_constants
  implicit none

  character(len=*), parameter :: EWTS_KEY_NGEN = "ngen"
  character(len=*), parameter :: EWTS_ID_NGEN  = "NGEN"

  character(len=*), parameter :: EWTS_KEY_CFE_S = "cfe-s"
  character(len=*), parameter :: EWTS_ID_CFE_S  = "CFE"

  character(len=*), parameter :: EWTS_KEY_CFE_X = "cfe-x"
  character(len=*), parameter :: EWTS_ID_CFE_X  = "CFE"

  character(len=*), parameter :: EWTS_KEY_FORCING = "forcing"
  character(len=*), parameter :: EWTS_ID_FORCING  = "FORCING"

  character(len=*), parameter :: EWTS_KEY_LASAM = "lasam"
  character(len=*), parameter :: EWTS_ID_LASAM  = "LASAM"

  character(len=*), parameter :: EWTS_KEY_LSTM = "lstm"
  character(len=*), parameter :: EWTS_ID_LSTM  = "LSTM"

  character(len=*), parameter :: EWTS_KEY_NOAH_OWP_MODULAR = "noah-owp-modular"
  character(len=*), parameter :: EWTS_ID_NOAH_OWP_MODULAR  = "NOAHOWP"

  character(len=*), parameter :: EWTS_KEY_PET = "pet"
  character(len=*), parameter :: EWTS_ID_PET  = "PET"

  character(len=*), parameter :: EWTS_KEY_SAC_SMA = "sac-sma"
  character(len=*), parameter :: EWTS_ID_SAC_SMA  = "SACSMA"

  character(len=*), parameter :: EWTS_KEY_SFT = "sft"
  character(len=*), parameter :: EWTS_ID_SFT  = "SFT"

  character(len=*), parameter :: EWTS_KEY_SNOW_17 = "snow-17"
  character(len=*), parameter :: EWTS_ID_SNOW_17  = "SNOW17"

  character(len=*), parameter :: EWTS_KEY_SMP = "smp"
  character(len=*), parameter :: EWTS_ID_SMP  = "SMP"

  character(len=*), parameter :: EWTS_KEY_TOPMODEL = "topmodel"
  character(len=*), parameter :: EWTS_ID_TOPMODEL  = "TOPMODEL"

  character(len=*), parameter :: EWTS_KEY_TOPOFLOW_GLACIER = "topoflow-glacier"
  character(len=*), parameter :: EWTS_ID_TOPOFLOW_GLACIER  = "TFGLACR"

  character(len=*), parameter :: EWTS_KEY_T_ROUTE = "t-route"
  character(len=*), parameter :: EWTS_ID_T_ROUTE  = "TROUTE"

  character(len=*), parameter :: EWTS_KEY_UEB = "ueb"
  character(len=*), parameter :: EWTS_ID_UEB  = "UEB_BMI"

end module ewts_module_constants
