! AUTO-GENERATED FILE. DO NOT EDIT.
! Generated by tools/generate_language_constants.py
! Generated (UTC): 2026-03-17T15:19:45Z
! Module registry: spec/module_registry.yaml
! Module registry version: 1

module ewts_module_constants
  implicit none

  character(len=*), parameter :: EWTS_KEY_NOAH_OWP_MODULAR = "noah-owp-modular"
  character(len=*), parameter :: EWTS_ID_NOAH_OWP_MODULAR  = "NOAHOWP"

  character(len=*), parameter :: EWTS_KEY_SAC_SMA = "sac-sma"
  character(len=*), parameter :: EWTS_ID_SAC_SMA  = "SACSMA"

  character(len=*), parameter :: EWTS_KEY_SNOW_17 = "snow-17"
  character(len=*), parameter :: EWTS_ID_SNOW_17  = "SNOW17"

end module ewts_module_constants
