#!/usr/bin/env python3
from __future__ import annotations

import argparse
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

try:
    import yaml  # PyYAML
except ImportError as e:
    raise SystemExit("Missing dependency: pyyaml. Install with: pip install pyyaml") from e

GENERATED_FILES: List[Path] = []
EWTS_ID_WIDTH = 8

# Canonical numeric levels (Python-style)
LEVELS = {
    "NOTSET": 0,
    "DEBUG": 10,
    "INFO": 20,
    "WARNING": 30,
    "ERROR": 40,
    "SEVERE": 40,
    "FATAL": 50,
    "CRITICAL": 50,
}

DEFAULT_LEVEL_NAME = "INFO"


@dataclass(frozen=True)
class Module:
    key: str
    ewts_id: str
    description: str = ""


def _infer_repo_root_from_script(script_path: Path) -> Path:
    # If this script lives at <repo>/tools/generate_language_constants.py
    # then repo root is the parent of the tools dir.
    return script_path.resolve().parent.parent


def _load_registry(registry_path: Path) -> List[Module]:
    data = yaml.safe_load(registry_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or "modules" not in data or not isinstance(data["modules"], list):
        raise SystemExit("Registry must be a YAML mapping with a top-level 'modules' list.")

    modules: List[Module] = []
    for i, raw in enumerate(data["modules"]):
        if not isinstance(raw, dict):
            raise SystemExit(f"Registry entry #{i} must be a mapping.")
        key = str(raw.get("key", "")).strip()
        ewts_id = str(raw.get("ewts_id", "")).strip()
        desc = str(raw.get("description", "")).strip()

        if not key:
            raise SystemExit(f"Registry entry #{i} has an empty 'key'.")
        if not ewts_id:
            raise SystemExit(f"Registry entry #{i} has an empty 'ewts_id'.")
        if len(ewts_id) > EWTS_ID_WIDTH:
            raise SystemExit(f"Registry entry #{i} ewts_id '{ewts_id}' exceeds {EWTS_ID_WIDTH} chars.")
        if ewts_id.upper() != ewts_id:
            raise SystemExit(f"Registry entry #{i} ewts_id '{ewts_id}' must be uppercase.")
        modules.append(Module(key=key, ewts_id=ewts_id, description=desc))
    return modules


def _validate_registry(modules: List[Module]) -> None:
    # Keys must be unique
    seen: Dict[str, int] = {}
    for i, m in enumerate(modules):
        if m.key in seen:
            j = seen[m.key]
            raise SystemExit(f"Duplicate module key '{m.key}' at entries {j} and {i}. Keys must be unique.")
        seen[m.key] = i
    # NOTE: ewts_id values are allowed to be duplicated (e.g., aliases like CFE)
    # so no uniqueness check here.


def _c_identifier_from_key(key: str) -> str:
    # Uppercase, non-alnum -> '_', collapse repeats
    out = []
    prev_us = False
    for ch in key.upper():
        if ch.isalnum():
            out.append(ch)
            prev_us = False
        else:
            if not prev_us:
                out.append("_")
                prev_us = True
    s = "".join(out).strip("_")
    while "__" in s:
        s = s.replace("__", "_")
    return s


def _ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _write_text(path: Path, content: str) -> None:
    _ensure_parent(path)
    path.write_text(content, encoding="utf-8")
    GENERATED_FILES.append(path)


def _banner(lang: str) -> str:
    return (
        "/* AUTO-GENERATED FILE. DO NOT EDIT.\n"
        " * Generated by tools/generate_language_constants.py\n"
        f" * Language: {lang}\n"
        " */\n"
    )


def _py_banner() -> str:
    return (
        "# AUTO-GENERATED FILE. DO NOT EDIT.\n"
        "# Generated by tools/generate_language_constants.py\n"
    )


def _generate_c_module_keys(modules: List[Module], out_h: Path) -> None:
    entries = []
    for m in modules:
        desc = m.description.replace('"', '\\"')
        entries.append(
            f'    {{"{m.key}", "{m.ewts_id}", "{desc}"}}'
        )

    content = _banner("C") + textwrap.dedent(f"""\
        #ifndef EWTS_MODULE_KEYS_H
        #define EWTS_MODULE_KEYS_H

        #include <stddef.h>

        #ifdef __cplusplus
        extern "C" {{
        #endif

        typedef struct {{
            const char* key;
            const char* ewts_id;
            const char* description;
        }} ewts_module_entry;

        extern const ewts_module_entry ewts_modules[];
        extern const size_t ewts_modules_count;

        // key -> ewts_id / description (returns NULL if not found)
        const char* ewts_module_id_from_key(const char* key);
        const char* ewts_description_from_key(const char* key);

        // ewts_id -> keys / descriptions (duplicates supported)
        // Returns number of matches. If out_* is NULL or max_* is 0, the function just counts.
        size_t ewts_keys_from_module_id(const char* ewts_id, const char** out_keys, size_t max_keys);
        size_t ewts_descriptions_from_module_id(const char* ewts_id, const char** out_descs, size_t max_descs);

        // Convenience helpers: return first match in registry order, or NULL if none.
        const char* ewts_first_key_from_module_id(const char* ewts_id);
        const char* ewts_first_description_from_module_id(const char* ewts_id);

        #ifdef __cplusplus
        }}  // extern "C"
        #endif

        #endif  // EWTS_MODULE_KEYS_H
    """)

    entries_block = ",\\n".join(entries)
    impl = _banner("C") + textwrap.dedent(f"""\
        #include "ewts/module_keys.h"
        #include <string.h>

        const ewts_module_entry ewts_modules[] = {{
            {entries_block}
        }};

        const size_t ewts_modules_count = sizeof(ewts_modules) / sizeof(ewts_modules[0]);

        const char* ewts_module_id_from_key(const char* key) {{
            if (!key) return NULL;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].key, key) == 0) {{
                    return ewts_modules[i].ewts_id;
                }}
            }}
            return NULL;
        }}

        const char* ewts_description_from_key(const char* key) {{
            if (!key) return NULL;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].key, key) == 0) {{
                    return ewts_modules[i].description;
                }}
            }}
            return NULL;
        }}

        size_t ewts_keys_from_module_id(const char* ewts_id, const char** out_keys, size_t max_keys) {{
            if (!ewts_id) return 0;
            size_t n = 0;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {{
                    if (out_keys && n < max_keys) {{
                        out_keys[n] = ewts_modules[i].key;
                    }}
                    ++n;
                }}
            }}
            return n;
        }}

        size_t ewts_descriptions_from_module_id(const char* ewts_id, const char** out_descs, size_t max_descs) {{
            if (!ewts_id) return 0;
            size_t n = 0;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {{
                    if (out_descs && n < max_descs) {{
                        out_descs[n] = ewts_modules[i].description;
                    }}
                    ++n;
                }}
            }}
            return n;
        }}

        const char* ewts_first_key_from_module_id(const char* ewts_id) {{
            if (!ewts_id) return NULL;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {{
                    return ewts_modules[i].key;
                }}
            }}
            return NULL;
        }}

        const char* ewts_first_description_from_module_id(const char* ewts_id) {{
            if (!ewts_id) return NULL;
            for (size_t i = 0; i < ewts_modules_count; ++i) {{
                if (strcmp(ewts_modules[i].ewts_id, ewts_id) == 0) {{
                    return ewts_modules[i].description;
                }}
            }}
            return NULL;
        }}
    """)

    # C output is two files: header + a small .c to provide the arrays and functions.
    # Keep consistent with existing output layout: put .c next to include tree under runtime/c/src.
    out_c = out_h.parents[2] / "src" / "ewts" / "module_keys.c"
    _write_text(out_h, content)
    _write_text(out_c, impl)


def _generate_c_log_levels(out_h: Path) -> None:
    # Header-only mapping for numeric -> name.
    cases = "\n".join([f'        case {v}: return "{k}";' for k, v in sorted(LEVELS.items(), key=lambda kv: kv[1])])
    content = _banner("C") + textwrap.dedent(f"""\
        #ifndef EWTS_LOG_LEVELS_H
        #define EWTS_LOG_LEVELS_H

        #ifdef __cplusplus
        extern "C" {{
        #endif

        static inline const char* ewts_log_level_name(int level) {{
            switch (level) {{
    {cases}
                default: return "{DEFAULT_LEVEL_NAME}";
            }}
        }}

        #ifdef __cplusplus
        }}  // extern "C"
        #endif

        #endif  // EWTS_LOG_LEVELS_H
    """)
    _write_text(out_h, content)


def _generate_cpp_module_keys(modules: List[Module], out_hpp: Path) -> None:
    # Provide a POD array for deterministic lookups + simple helper functions.
    entries = []
    for m in modules:
        desc = m.description.replace("\\", "\\\\").replace('"', '\\"')
        entries.append(f'    {{"{m.key}", "{m.ewts_id}", "{desc}"}}')

    entries_block = ",\\n".join(entries)
    content = textwrap.dedent(f"""\
        // AUTO-GENERATED FILE. DO NOT EDIT.
        // Generated by tools/generate_language_constants.py

        #ifndef EWTS_MODULE_KEYS_HPP
        #define EWTS_MODULE_KEYS_HPP

        #include <cstddef>
        #include <cstring>
        #include <vector>

        namespace ewts {{
        struct ModuleEntry {{
            const char* key;
            const char* ewts_id;
            const char* description;
        }};

        static const ModuleEntry kModules[] = {{
            {entries_block}
        }};

        static const std::size_t kModulesCount = sizeof(kModules) / sizeof(kModules[0]);

        inline const char* EwtsIdFromKey(const char* key) {{
            if (!key) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].key, key) == 0) return kModules[i].ewts_id;
            }}
            return nullptr;
        }}

        inline const char* DescriptionFromKey(const char* key) {{
            if (!key) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].key, key) == 0) return kModules[i].description;
            }}
            return nullptr;
        }}

        inline std::vector<const char*> KeysFromEwtsId(const char* ewts_id) {{
            std::vector<const char*> out;
            if (!ewts_id) return out;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) out.push_back(kModules[i].key);
            }}
            return out;
        }}

        inline std::vector<const char*> DescriptionsFromEwtsId(const char* ewts_id) {{
            std::vector<const char*> out;
            if (!ewts_id) return out;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) out.push_back(kModules[i].description);
            }}
            return out;
        }}

        inline const char* FirstKeyFromEwtsId(const char* ewts_id) {{
            if (!ewts_id) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) return kModules[i].key;
            }}
            return nullptr;
        }}

        inline const char* FirstDescriptionFromEwtsId(const char* ewts_id) {{
            if (!ewts_id) return nullptr;
            for (std::size_t i = 0; i < kModulesCount; ++i) {{
                if (std::strcmp(kModules[i].ewts_id, ewts_id) == 0) return kModules[i].description;
            }}
            return nullptr;
        }}

        }}  // namespace ewts

        #endif  // EWTS_MODULE_KEYS_HPP
    """)
    _write_text(out_hpp, content)


def _generate_cpp_log_levels(out_hpp: Path) -> None:
    cases = "\n".join([f'    if (level == {v}) return "{k}";' for k, v in sorted(LEVELS.items(), key=lambda kv: kv[1])])
    content = textwrap.dedent(f"""\
        // AUTO-GENERATED FILE. DO NOT EDIT.
        // Generated by tools/generate_language_constants.py

        #ifndef EWTS_LOG_LEVELS_HPP
        #define EWTS_LOG_LEVELS_HPP

        namespace ewts {{
        inline const char* LogLevelName(int level) {{
    {cases}
            return "{DEFAULT_LEVEL_NAME}";
        }}
        }}  // namespace ewts

        #endif  // EWTS_LOG_LEVELS_HPP
    """)
    _write_text(out_hpp, content)


def _generate_fortran_module_keys(modules: List[Module], out_f90: Path) -> None:
    # Fixed-length strings; choose conservative lengths
    max_key = max(len(m.key) for m in modules)
    max_id = max(len(m.ewts_id) for m in modules)
    max_desc = max((len(m.description) for m in modules), default=0)
    max_key = max(max_key, 1)
    max_id = max(max_id, 1)
    max_desc = max(max_desc, 1)

    keys = ", ".join([f'"{m.key}"' for m in modules])
    ids = ", ".join([f'"{m.ewts_id}"' for m in modules])
    descs = ", ".join([f'"{m.description.replace(chr(34), "")}"' for m in modules])  # strip quotes

    content = textwrap.dedent(f"""\
        ! AUTO-GENERATED FILE. DO NOT EDIT.
        ! Generated by tools/generate_language_constants.py

        module ewts_module_keys
          implicit none

          integer, parameter :: EWTS_MODULE_COUNT = {len(modules)}
          integer, parameter :: EWTS_KEY_LEN = {max_key}
          integer, parameter :: EWTS_ID_LEN = {max_id}
          integer, parameter :: EWTS_DESC_LEN = {max_desc}

          character(len=EWTS_KEY_LEN), dimension(EWTS_MODULE_COUNT), parameter :: EWTS_KEYS = (/ {keys} /)
          character(len=EWTS_ID_LEN),  dimension(EWTS_MODULE_COUNT), parameter :: EWTS_IDS  = (/ {ids} /)
          character(len=EWTS_DESC_LEN),dimension(EWTS_MODULE_COUNT), parameter :: EWTS_DESCS= (/ {descs} /)

        contains

          pure function ewts_id_from_key(key) result(ewts_id)
            character(len=*), intent(in) :: key
            character(len=EWTS_ID_LEN) :: ewts_id
            integer :: i
            ewts_id = ""
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_KEYS(i)) == trim(key)) then
                ewts_id = EWTS_IDS(i)
                return
              end if
            end do
          end function ewts_id_from_key

          pure function ewts_description_from_key(key) result(desc)
            character(len=*), intent(in) :: key
            character(len=EWTS_DESC_LEN) :: desc
            integer :: i
            desc = ""
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_KEYS(i)) == trim(key)) then
                desc = EWTS_DESCS(i)
                return
              end if
            end do
          end function ewts_description_from_key

          subroutine ewts_keys_from_id(ewts_id, out_keys, n)
            character(len=*), intent(in) :: ewts_id
            character(len=*), dimension(:), intent(out) :: out_keys
            integer, intent(out) :: n
            integer :: i, k
            n = 0
            k = 0
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_IDS(i)) == trim(ewts_id)) then
                n = n + 1
                if (k < size(out_keys)) then
                  k = k + 1
                  out_keys(k) = trim(EWTS_KEYS(i))
                end if
              end if
            end do
          end subroutine ewts_keys_from_id

          subroutine ewts_descs_from_id(ewts_id, out_descs, n)
            character(len=*), intent(in) :: ewts_id
            character(len=*), dimension(:), intent(out) :: out_descs
            integer, intent(out) :: n
            integer :: i, k
            n = 0
            k = 0
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_IDS(i)) == trim(ewts_id)) then
                n = n + 1
                if (k < size(out_descs)) then
                  k = k + 1
                  out_descs(k) = trim(EWTS_DESCS(i))
                end if
              end if
            end do
          end subroutine ewts_descs_from_id

          pure function ewts_first_key_from_id(ewts_id) result(key)
            character(len=*), intent(in) :: ewts_id
            character(len=EWTS_KEY_LEN) :: key
            integer :: i
            key = ""
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_IDS(i)) == trim(ewts_id)) then
                key = EWTS_KEYS(i)
                return
              end if
            end do
          end function ewts_first_key_from_id

          pure function ewts_first_desc_from_id(ewts_id) result(desc)
            character(len=*), intent(in) :: ewts_id
            character(len=EWTS_DESC_LEN) :: desc
            integer :: i
            desc = ""
            do i = 1, EWTS_MODULE_COUNT
              if (trim(EWTS_IDS(i)) == trim(ewts_id)) then
                desc = EWTS_DESCS(i)
                return
              end if
            end do
          end function ewts_first_desc_from_id

        end module ewts_module_keys
    """)
    _write_text(out_f90, content)


def _generate_fortran_log_levels(out_f90: Path) -> None:
    # Provide a function mapping integer->name.
    content = textwrap.dedent(f"""\
        ! AUTO-GENERATED FILE. DO NOT EDIT.
        ! Generated by tools/generate_language_constants.py

        module ewts_log_levels
          implicit none
        contains
          pure function ewts_log_level_name(level) result(name)
            integer, intent(in) :: level
            character(len=16) :: name
            select case (level)
    """)
    for k, v in sorted(LEVELS.items(), key=lambda kv: kv[1]):
        content += f'            case ({v})\n              name = "{k}"\n'
    content += textwrap.dedent(f"""\
            case default
              name = "{DEFAULT_LEVEL_NAME}"
            end select
          end function ewts_log_level_name
        end module ewts_log_levels
    """)
    _write_text(out_f90, content)


def _generate_python_module_keys(modules: List[Module], out_py: Path) -> None:
    # key -> ewts_id / desc
    key_to_id = {m.key: m.ewts_id for m in modules}
    key_to_desc = {m.key: m.description for m in modules}

    # ewts_id -> list of keys / descs (preserve registry order)
    id_to_keys: Dict[str, List[str]] = {}
    id_to_descs: Dict[str, List[str]] = {}
    for m in modules:
        id_to_keys.setdefault(m.ewts_id, []).append(m.key)
        id_to_descs.setdefault(m.ewts_id, []).append(m.description)

    lines = [_py_banner(), "from __future__ import annotations\n", "from typing import Dict, List, Optional\n\n"]
    lines.append(f"KEY_TO_EWTS_ID: Dict[str, str] = {key_to_id!r}\n")
    lines.append(f"KEY_TO_DESCRIPTION: Dict[str, str] = {key_to_desc!r}\n")
    lines.append(f"EWTS_ID_TO_KEYS: Dict[str, List[str]] = {id_to_keys!r}\n")
    lines.append(f"EWTS_ID_TO_DESCRIPTIONS: Dict[str, List[str]] = {id_to_descs!r}\n\n")

    lines.append(textwrap.dedent("""\
        def ewts_id_from_key(key: str) -> Optional[str]:
            \"\"\"Return EWTS module id for a key, or None if unknown.\"\"\"
            return KEY_TO_EWTS_ID.get(key)

        def description_from_key(key: str) -> Optional[str]:
            \"\"\"Return description for a key, or None if unknown.\"\"\"
            return KEY_TO_DESCRIPTION.get(key)

        def keys_from_ewts_id(ewts_id: str) -> List[str]:
            \"\"\"Return all keys that map to an EWTS id (duplicates supported).\"\"\"
            return list(EWTS_ID_TO_KEYS.get(ewts_id, []))

        def descriptions_from_ewts_id(ewts_id: str) -> List[str]:
            \"\"\"Return all descriptions for an EWTS id (duplicates supported).\"\"\"
            return list(EWTS_ID_TO_DESCRIPTIONS.get(ewts_id, []))

        def first_key_from_ewts_id(ewts_id: str) -> Optional[str]:
            \"\"\"Return the first key for an EWTS id in registry order, or None.\"\"\"
            keys = EWTS_ID_TO_KEYS.get(ewts_id)
            return keys[0] if keys else None

        def first_description_from_ewts_id(ewts_id: str) -> Optional[str]:
            \"\"\"Return the first description for an EWTS id in registry order, or None.\"\"\"
            descs = EWTS_ID_TO_DESCRIPTIONS.get(ewts_id)
            return descs[0] if descs else None
    """))

    _write_text(out_py, "".join(lines))


def _generate_python_log_levels(out_py: Path) -> None:
    lines = [_py_banner(), "from __future__ import annotations\n\n", f"LEVELS = {LEVELS!r}\n\n"]
    lines.append(textwrap.dedent(f"""\
        def log_level_name(level: int) -> str:
            for name, val in LEVELS.items():
                if val == level:
                    return name
            return "{DEFAULT_LEVEL_NAME}"
    """))
    _write_text(out_py, "".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate per-language EWTS module keys and log-level constants from a YAML registry."
    )
    ap.add_argument(
        "--registry",
        default="tools/module_registry.yaml",
        help="Path to the module registry YAML file, relative to the repo root. (default: tools/module_registry.yaml)",
    )
    ap.add_argument(
        "--repo-root",
        default=None,
        help="Optional explicit path to the repository root. If not provided, the repo root is inferred as the parent-of-parent directory of this script.",
    )
    args = ap.parse_args()

    script_path = Path(__file__).resolve()
    repo_root = Path(args.repo_root).resolve() if args.repo_root else _infer_repo_root_from_script(script_path)
    registry_path = (repo_root / args.registry).resolve()

    modules = _load_registry(registry_path)
    _validate_registry(modules)

    # Outputs (match the documented layout)
    c_mod_h = repo_root / "runtime" / "c" / "include" / "ewts" / "module_keys.h"
    c_lvl_h = repo_root / "runtime" / "c" / "include" / "ewts" / "log_levels.h"

    cpp_mod_hpp = repo_root / "runtime" / "cpp" / "include" / "ewts" / "module_keys.hpp"
    cpp_lvl_hpp = repo_root / "runtime" / "cpp" / "include" / "ewts" / "log_levels.hpp"

    f_mod_f90 = repo_root / "runtime" / "fortran" / "src" / "ewts" / "module_keys.f90"
    f_lvl_f90 = repo_root / "runtime" / "fortran" / "src" / "ewts" / "log_levels.f90"

    py_mod_py = repo_root / "runtime" / "python" / "ewts" / "src" / "ewts" / "module_keys.py"
    py_lvl_py = repo_root / "runtime" / "python" / "ewts" / "src" / "ewts" / "log_levels.py"

    _generate_c_module_keys(modules, c_mod_h)
    _generate_c_log_levels(c_lvl_h)

    _generate_cpp_module_keys(modules, cpp_mod_hpp)
    _generate_cpp_log_levels(cpp_lvl_hpp)

    _generate_fortran_module_keys(modules, f_mod_f90)
    _generate_fortran_log_levels(f_lvl_f90)

    _generate_python_module_keys(modules, py_mod_py)
    _generate_python_log_levels(py_lvl_py)

    print("Wrote per-language constants for modules + log levels.\n")

    print("Generated files:")
    for path in GENERATED_FILES:
        try:
            rel = path.relative_to(repo_root)
        except ValueError:
            rel = path
        print(f"  - {rel}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
